{% set name = "voeventlib" %}
{% set version = "1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # voeventlib-1.2 on pypi only provides wheels, not a tarball,
  # so we build from the relevant git commit in the upstream repo.
  # Reported as: https://git.ligo.org/emfollow/VOEventLib/issues/2
  git_url: https://git.ligo.org/emfollow/VOEventLib
  git_tag: 2452c5b81d6d6051b210f62355824ec7885669c1

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - VOEventLib
    - VOEventLib.VOEvent
    - VOEventLib.Vutil

about:
  home: https://git.ligo.org/emfollow/VOEventLib
  dev_url: https://git.ligo.org/emfollow/VOEventLib
  license: GPLv3+
  license_family: GPL
  license_file: LICENSE.md
  summary: Python library to read, modify, and create VOEvents
  description: Python library to read, modify, and create VOEvents

extra:
  recipe-maintainers:
    - duncanmmacleod
