travis:
  secure:
    BINSTAR_TOKEN: am8KdxdNvvKN12J3n36uSaqcZ3uMd4SgPpkdCDAIHfsCUoy8nLpvGSjdv7SpPqXsVCXXbogBV4FQOHBV/0ip3kePDnrXjg+fxb5tTBC6Ms5CM0yAVu1rYxy0SEVRFkV/5mrQuvWYz07SPX4CzDNqKmP21jcqyd1om0ZfKE9qM/MFL0BEbFs1cyP7X4HBDJaiT9trgtqjM+d6MI6uC8xHbRwRne45+noDGncgmnEAaz8yiJ4FAiuCE8RiVACfJVCF8a8njG8PNJ7ubrw/FHVjE3U1IrpDHljtTGq9/Wk40RV13U4M08pMWwj5JRouZ8XETttD4HMN6hB362INv8MdlFC/Pt/gDuqCkANuKysradanb24XirHFCJo03qrol61xTk5+IwOWK8H+jqz8/wMD8CCB3lp/elpkHD1WrtIpq7Kg7tPxM7DsoYEV9F2Ajpd0TtqA16GRebvZ2za5zXoWiio8FQyxw+G8Iv3H6j6whW2yUGtayoIrz7OAlMJk6ov5u5jUYbaBjD9hPMw9uCCqptBmUTQuGo44rY2gRfbFcXJWTx0ufj/N6qCNofcD+r1Ifbz47fijcvDcjevSHVjsUQUbEWeA4+XUh2W/cxE3P0VQD1YiVzvp9i86agYN+e60DLHtO95vQThjKxwUEs8WRZ7BM4KC0sZWp15AOpgrs2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
